import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/organisms/Navbar";

import { Poppins } from "next/font/google";
import { Oleo_Script_Swash_Caps } from "next/font/google";
import Footer from "@/components/organisms/Footer";
import FooterAlt from "@/components/organisms/FooterAlt";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const oleo = Oleo_Script_Swash_Caps({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-oleo",
});
export const metadata: Metadata = {
  title: "Secret Marina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${oleo.variable}`}>
      <body>
        <Navbar />

        {children}
        <Footer />
        {/* <FooterAlt/> */}
      </body>
    </html>
  );
}
