import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Poppins, Oleo_Script_Swash_Caps } from "next/font/google";
import { Providers } from "./providers";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import Navbar from "@/components/organisms/Navbar";
import Footer from "@/components/organisms/Footer";
import AuthDialog from "@/features/auth/AuthDialog";
import { cookies } from "next/headers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const oleo = Oleo_Script_Swash_Caps({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-oleo",
});

export const metadata: Metadata = {
  title: "Secret Marina",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
  // params: { locale: string };
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params;

  let messages;
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (err) {
    notFound();
  }

  const cookieStore = await cookies();
  const token = cookieStore.get("auth_token")?.value;
  const isAuth = !!token;

  return (
    <html lang={locale} dir={`${locale === "ar" ? "rtl" : "ltr"}`}>
      <body className={`${poppins.variable} ${oleo.variable}`}>
        <Providers>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Navbar isAuth={isAuth} />
            {children}
            <AuthDialog />
            <Footer />
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
